# Generated by Django 4.2.20 on 2025-05-01 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bnpl', '0002_paymentplan_start_date_paymentplan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installment',
            name='user',
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
